- hosts: all
  become: true

  tasks:
    - name: upgrade
      yum:      
        name: "*"
        state: latest

    - name: Install MySQL
      yum: name={{ item }} state=latest
      with_items:
        - default-mysql-server

    - name: Start the MySQL service
      action: service name=mysqld state=started


